<?php

/**********************************************************************

* THE FIELDS

**********************************************************************/
function wp_tac_settings_fields_val() {

	$gaUa = get_QodeOptions('google_analytics_code');

	$section_1_fields = array (
		array(
			'field_id'		=> 'field-1-1',
			'label'			=> __( 'Google jsapi', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-1',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( '', 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'jsapi',
			'enqueue'		=> '',
			'marqueur'		=> '',
			'jobuser'		=> '',
			'placeholder'	=> '',
		),
		array(
			'field_id'		=> 'field-1-2',
			'label'			=> __( 'Google Maps', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-1',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( '', 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'googlemaps',
			'enqueue'		=> 'google_map_api',
			'marqueur'		=> '',
			'jobuser'		=> 'key',
			'placeholder'	=> 'key api',
//			'search'		=> array(
//				'ereg'			=> '~data-height="(.*)" style="(.*)" .*\s*.*(<div .*><\/div>).*\s*.*(<div .*><\/div>)~',
//				'replace'		=> '<div class="googlemaps-canvas google_map" id="map_canvas" zoom="$zoom" latitude="$latitude" longitude="$longitude" style="width: $widthpx; height: $heightpx;"></div>',
//			),
//			'optionnal'		=> array(
//				'zoom'		=> 'dark', /* zoom (int) */
//				'latitude'	=> '', /* zoom (int) */
//				'longitude'	=> '', /* zoom (int) */
//				'widthpx'	=> '', /* zoom (int) */
//				'heightpx'	=> '', /* zoom (int) */
//			),
		),
//		array(
//			'field_id'		=> 'field-1-3',
//			'label'			=> __( 'Google Tag Manager', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'	 	=> 'wp_tac-plugin',
//			'section_name'	=> 'section-1',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-1-4',
//			'label'			=> __( 'Timeline JS', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'	 	=> 'wp_tac-plugin',
//			'section_name'	=> 'section-1',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'	 	=> 'field-1-5',
//			'label'		 	=> __( 'Typekit (adobe)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-1',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
	);
	$section_2_fields = array (
//		array(
//			'field_id'		=> 'field-2-1',
//			'label'			=> __( 'Disqus', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-2',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-2-2',
//			'label'			=> __( 'Facebook (commentaire)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-2',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
	);
	$section_3_fields = array (
//		array(
//			'field_id'		=> 'field-3-1',
//			'label'			=> __( 'Alexa', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-2',
//			'label'			=> __( 'Clicky', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-3',
//			'label'			=> __( 'Crazy Egg', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-4',
//			'label'			=> __( 'eTracker', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-6',
//			'label'			=> __( 'FERank', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-7',
//			'label'			=> __( 'Get+', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
		array(
			'field_id'		=> 'field-3-8',
			'label'			=> __( 'Google Analytics (ga.js)', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-3',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( $gaUa, 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'gajs',
			'enqueue'		=> '',
			'marqueur'		=> '',
			'jobuser'		=> 'gajsUa',
			'placeholder'	=> '',
			'more'			=> array('gajsMore', "_gaq.push (['_gat._anonymizeIp']); _gaq.push (['_trackPageview']);"),
		),
		array(
			'field_id'		=> 'field-3-9',
			'label'			=> __( 'Google Analytics (gtag.js)', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-3',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( $gaUa, 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'gtag',
			'enqueue'		=> '',
			'marqueur'		=> '',
			'jobuser'		=> 'gtagUa',
			'placeholder'	=> '',
			'more'			=> array('gtagMore', "gtag('config', tarteaucitron.user.gtagUa, { 'anonymize_ip': true });"),
		),
		array(
			'field_id'		=> 'field-3-10',
			'label'			=> __( 'Google Analytics (universal)', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-3',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( $gaUa, 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'analytics',
			'enqueue'		=> '',
			'marqueur'		=> '',
			'jobuser'		=> 'analyticsUa',
			'placeholder'	=> '',
			'more'			=> array('analyticsMore', "ga('set', 'anonymizeIp', true);ga('send', 'pageview');"),
		),
//		array(
//			'field_id'		=> 'field-3-11',
//			'label'			=> __( 'Microsoft Campaign Analytics', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-12',
//			'label'			=> __( 'StatCounter', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-13',
//			'label'			=> __( 'VisualRevenue', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-14',
//			'label'			=> __( 'Wysistat', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-3-15',
//			'label'			=> __( 'Xiti', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-3',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
	);
	$section_4_fields = array (
//		array(
//			'field_id'		=> 'field-4-1',
//			'label'			=> __( 'Amazon', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-2',
//			'label'			=> __( 'Clicmanager', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-3',
//			'label'			=> __( 'Criteo', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-4',
//			'label'			=> __( 'Dating Affiliation', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-5',
//			'label'			=> __( 'Dating Affiliation (popup)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-6',
//			'label'			=> __( 'FERank (pub)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-7',
//			'label'			=> __( 'Google Adsense', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-8',
//			'label'			=> __( 'Google Adsense Search (form)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-9',
//			'label'			=> __( 'Google Adsense Search (result)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-10',
//			'label'			=> __( 'Google Adwords (conversion)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-11',
//			'label'			=> __( 'Google Adwords (remarketing)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-12',
//			'label'			=> __( 'Prelinker', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-13',
//			'label'			=> __( 'Pubdirecte', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-14',
//			'label'			=> __( 'ShareASale', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-15',
//			'label'			=> __( 'Twenga', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-4-16',
//			'label'			=> __( 'vShop', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-4',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
	);
	$section_5_fields = array (
//		array(
//			'field_id'		=> 'field-5-1',
//			'label'			=> __( 'AddThis', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-2',
//			'label'			=> __( 'AddToAny (feed)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-3',
//			'label'			=> __( 'AddToAny (share)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-4',
//			'label'			=> __( 'eKomi', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-5',
//			'label'			=> __( 'Facebook', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-6',
//			'label'			=> __( 'Facebook (like box)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-7',
//			'label'			=> __( 'Facebook Pixel', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-8',
//			'label'			=> __( 'Google+', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-9',
//			'label'			=> __( 'Google+ (badge)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-10',
//			'label'			=> __( 'Linkedin', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-11',
//			'label'			=> __( 'Pinterest', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-12',
//			'label'			=> __( 'Shareaholic', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-13',
//			'label'			=> __( 'ShareThis', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-14',
//			'label'			=> __( 'Twitter', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-15',
//			'label'			=> __( 'Twitter (cards)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-5-16',
//			'label'			=> __( 'Twitter (timelines)', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-5',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
	);
	$section_6_fields = array (
//		array(
//			'field_id'		=> 'field-6-1',
//			'label'			=> __( 'PureChat', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-6',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-6-2',
//			'label'			=> __( 'UserVoice', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-6',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-6-3',
//			'label'			=> __( 'Zopim', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-6',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//			'job'			=> 'zopim',
//			'enqueue'		=> '',
//			'marqueur'		=> '',
//			'jobuser'		=> 'zopimID',
//			'placeholder'	=> 'zopim ID',
//		),
	);
	$section_7_fields = array (
//		array(
//			'field_id'		=> 'field-7-1',
//			'label'			=> __( 'Calaméo', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-7',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-7-2',
//			'label'			=> __( 'Dailymotion', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-7',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-7-3',
//			'label'			=> __( 'Prezi', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-7',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
//		array(
//			'field_id'		=> 'field-7-4',
//			'label'			=> __( 'SlideShare', 'wp-tac' ),
//			'field_callbk'	=> 'wp_tac_settings_field_callback',
//			'menu_slug'		=> 'wp_tac-plugin',
//			'section_name'	=> 'section-7',
//			'helper'		=> __( '', 'wp-tac' ),
//			'description'	=> __( '', 'wp-tac' ),
//			'default'		=> '',
//		),
		array(
			'field_id'		=> 'field-7-5',
			'label'			=> __( 'Vimeo', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-7',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( '', 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'vimeo',
			//'enqueue'		=> array( 'vimeo', 'mediaelement-vimeo' ),
			'enqueue'		=> 'mediaelement-vimeo',
			'marqueur'		=> '',
			'search'		=> array(
				'ereg'			=> '~.* .*src=".*vimeo\.com\/video\/(.*)\?.* width="([[:digit:]]*)" .*height="([[:digit:]]*)".*~',
				'replace'		=> '<div class="vimeo_player" videoID="%video_id" width="%width" height="%height"></div>',
			),
			'optionnal'		=> array(
			),
			'jobuser'		=> '',
			'placeholder'	=> 'ID Vidéo',
		),
		array(
			'field_id'		=> 'field-7-6',
			'label'			=> __( 'Youtube', 'wp-tac' ),
			'field_callbk'	=> 'wp_tac_settings_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-7',
			'helper'		=> __( '', 'wp-tac' ),
			'description'	=> __( '', 'wp-tac' ),
			'default'		=> '',
			'job'			=> 'youtube',
			'enqueue'		=> '',
			'marqueur'		=> '',
			'search'		=> array(
				'ereg'			=> '~.* width="(.*)".*height="(.*)" .*src="(.*youtu.*).*\?(.*)\"(.*)~',
				'replace'		=> '<div class="youtube_player tarteaucitron" videoID="%video_id" width="%width" height="%height" theme="%theme" rel="%rel" controls="%controls" showinfo="%showinfo" autoplay="%autoplay"></div>',
			),
			'optionnal'		=> array(
				'theme'			=> 'dark',	/* theme (dark | light) */
				'rel'			=> '0',		/* rel (1 | 0) */
				'controls'		=> '0',		/* controls (1 | 0) */
				'showinfo'		=> '0',		/* howinfo (1 | 0) */
				'autoplay'		=> '0',		/* autoplay (1 | 0) */
			),
			'jobuser'		=> '',
			'placeholder'	=> 'ID Vidéo',
		),
	);
	$section_fields = array(
		'section-1'	=> $section_1_fields,
		'section-2'	=> $section_2_fields,
		'section-3'	=> $section_3_fields,
		'section-4'	=> $section_4_fields,
		'section-5'	=> $section_5_fields,
		'section-6'	=> $section_6_fields,
		'section-7'	=> $section_7_fields,
	);

	return $section_fields ;
}


function wp_tac_settings_param_fields_val() {

	$section_1_fields = array (
		array( /* Ouverture automatique du panel avec le hashtag */
			'field_id'		=> 'field-1-1',
			'param_name'	=> 'hashtag', 
			'label'			=> __( 'hashtag', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> '#tarteaucitron',
		),
		array( /* d�sactiver le consentement implicite (en naviguant) ? */
			'field_id'		=> 'field-1-2',
			'param_name'	=> 'highPrivacy', 
			'label'			=> __( 'highPrivacy', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> false,
			'type'			=> 'checkbox',
		),
		array( /* le bandeau doit �tre en haut (top) ou en bas (bottom) ? */
			'field_id'		=> 'field-1-3',
			'param_name'	=> 'orientation', 
			'label'			=> __( 'orientation', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> 'bottom',
			'type'			=> 'select',
			'options'			=> array('top','bottom'),
		),
		array( /* Afficher un message si un adblocker est d�tect� */
			'field_id'		=> 'field-1-4',
			'param_name'	=> 'adblocker', 
			'label'			=> __( 'adblocker', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> false,
			'type'			=> 'checkbox',
		),
		array( /* afficher le petit bandeau en bas � droite ? */
			'field_id'		=> 'field-1-5',
			'param_name'	=> 'showAlertSmall', 
			'label'			=> __( 'showAlertSmall', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> false,
			'type'			=> 'checkbox',
		),
		array( /* Afficher la liste des cookies install�s ? */
			'field_id'		=> 'field-1-6',
			'param_name'	=> 'cookieslist', 
			'label'			=> __( 'cookieslist', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> true,
			'type'			=> 'checkbox',
		),
		array( /* supprimer le lien vers la source ? */
			'field_id'		=> 'field-1-7',
			'param_name'	=> 'removeCredit', 
			'label'			=> __( 'removeCredit', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> true,
			'type'			=> 'checkbox',
		),
		array( /* supprimer le lien vers la source ? */
			'field_id'		=> 'field-1-8',
			'param_name'	=> 'bypass', 
			'label'			=> __( 'bypass for visitor is not in the EU.', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> false,
			'type'			=> 'checkbox',
		),
		array( /* supprimer le lien vers la source ? */
			'field_id'		=> 'field-1-9',
			'param_name'	=> 'anonymizeIp', 
			'label'			=> __( 'Anonymize IP in Google Analytics', 'wp-tac' ), 
			'field_callbk'	=> 'wp_tac_settings_param_field_callback',
			'menu_slug'		=> 'wp_tac-plugin',
			'section_name'	=> 'section-p-1',
			'default'		=> false,
			'type'			=> 'checkbox',
		),
	);
	$section_fields = array(
		'section-p-1'	=> $section_1_fields,
	);

	return $section_fields ;
}


